name: edutech_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  connectivity_plus: null
  cupertino_icons: ^1.0.8
  dio: null
  file_picker: null
  firebase: ^9.0.3
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_chat_bubble: ^2.0.2
  flutter_dotenv: ^6.0.0
  flutter_svg: null
  font_awesome_flutter: null
  get: ^4.7.2
  gradient_borders: ^1.0.2
  http: null
  http_parser: null
  image_picker: null
  intl: null
  jwt_decoder: ^2.0.1
  mime: ^1.0.0
  provider: null
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/send.svg
    - .env

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
          weight: 400
        - asset: assets/fonts/Fredoka-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fredoka-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700
    - family: CascadiaCode
      fonts:
        - asset: assets/fonts/CascadiaCode-Bold.ttf
          weight: 700
