// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfvDwYj0xlFUnnW2jaDESPjq4VJf6v16U',
    appId: '1:182715579022:web:4090651601da7539f0e7df',
    messagingSenderId: '182715579022',
    projectId: 'edutech-app-eg',
    authDomain: 'edutech-app-eg.firebaseapp.com',
    storageBucket: 'edutech-app-eg.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAGzjwTCUOfyl57dvUOap5bIIloHirGlk',
    appId: '1:182715579022:android:92bc1c3ba862b09cf0e7df',
    messagingSenderId: '182715579022',
    projectId: 'edutech-app-eg',
    storageBucket: 'edutech-app-eg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqVOOGD7vkZQ2KwyNdvvJwmyciLafBGtA',
    appId: '1:182715579022:ios:c5630010e754147df0e7df',
    messagingSenderId: '182715579022',
    projectId: 'edutech-app-eg',
    storageBucket: 'edutech-app-eg.firebasestorage.app',
    iosBundleId: 'com.example.edutechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqVOOGD7vkZQ2KwyNdvvJwmyciLafBGtA',
    appId: '1:182715579022:ios:c5630010e754147df0e7df',
    messagingSenderId: '182715579022',
    projectId: 'edutech-app-eg',
    storageBucket: 'edutech-app-eg.firebasestorage.app',
    iosBundleId: 'com.example.edutechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfvDwYj0xlFUnnW2jaDESPjq4VJf6v16U',
    appId: '1:182715579022:web:d362aa47841e069ff0e7df',
    messagingSenderId: '182715579022',
    projectId: 'edutech-app-eg',
    authDomain: 'edutech-app-eg.firebaseapp.com',
    storageBucket: 'edutech-app-eg.firebasestorage.app',
  );
}
